Робота з рядком запиту.
ithillel-php-basic/php-basic-2-6415da42760e5708f2c96194 pull request #9
Opened 2023-05-22 14:53 UTC by yevgenii-v

- Для кожного проєкту в меню буде закріплене активне посилання. Якщо користувач переходить за посиланням йому буде виводитись список завдань, які належать
до вказаного проєкту.
- Додана перевірка на існування проєкту. Якщо користувач помилився з id або вказав проєкт, який не закріплений за користувачем, то його переведе на сторінку 404.

2023-05-22 15:39 UTC, alexpalyan requested changes

2023-05-22 15:39 UTC, alexpalyan commented on helpers.php
> +function isProjectExists(array $data)
Дуже хороше рішення використовувати створення фунції. Буде краще, якщо функція буде повертати true або false а вже код який буде її викликати то виставляє код відповіді та зупиняє обробку якщо треба )

2023-05-22 15:39 UTC, alexpalyan commented on templates/kanban.php
> +                        <?php if($task['status'] === 'in-progress' && isset($_GET['project_id']) && $task['project_id'] === $_GET['project_id']): ?>
Краще не звертатись до глобальних змінних напряму з шаблону ) Спробуй передати через створену змінну )

2023-05-22 15:39 UTC, alexpalyan commented on templates/kanban.php
> +                        <?php if ($task['status'] === 'to-do' && !isset($_GET['project_id'])): ?>
Краще не звертатись до глобальних змінних напряму з шаблону ) Спробуй передати через створену змінну )

2023-05-22 15:39 UTC, alexpalyan commented on index.php
> +    $tasksQuery = 'SELECT t.id, t.title, t.description, p.id as project_id, p.title as project_title, t.deadline, t.file, t.status, t.created_at
Тут кожен раз із бази вибираються всі задачі, без фільтру по проекту. Якщо задач дуже багато, то це буде створювати додаткове навантаження на систему. Спробуй зробити так щоби вибирались тільки задачі обраного проекту )

2023-05-23 06:39 UTC, alexpalyan requested changes

2023-05-23 06:39 UTC, alexpalyan commented on index.php
> +    }
Можна робити конкатенацію ) Та покласти під логіку додавання проекту
$tasksQuery = 'SELECT t.i ...
if (isset($_GET['project_id']) {
  $tasksQuery .= ' AND t.project_id =...
}
AND t.project_id .= ' GROUP BY t.id';

2023-05-23 06:39 UTC, alexpalyan commented on index.php
> +                       AND t.project_id = '.$_GET['project_id'].'
SQL Injection! :)

2023-05-23 06:39 UTC, alexpalyan commented on index.php
> +        $countTotalTasks = getQuery($db_connection, $countTasksQuery);
Змінна використовується поза цією гілкою, тож повинна бути об'явлена ) А взагалі ти вже вибираєш кількість по кожному проекту, можна просто підсумувати, логіка таким чином стане більш прозорою :)

2023-05-23 11:49 UTC, yevgenii-v commented on index.php
> +    }
О, навіть так можна...

2023-05-24 07:54 UTC, merged